### PR TITLE
Issue #31: added a simple showcase page with khalti, nlocate, and sparrow sms

### PR DESCRIPTION
**Pull request by code-geek**
A basic showcase page.

Todo:

- [ ] Add more applications
- [ ] Fix Styles

### CODE REVIEW

**Comment by kaflesudip** [comment]
Thanks. Let's use Markdown if possible. Also, you may not need to start from `<html>`. See other markdown pages or examples.

**Comment by code-geek** [comment]
Okay sure, I'll check and re-upload.

**Comment by amitness** [comment]
@code-geek Please checkout from `source` branch. The master branch is auto built by Travis.

You can look at the files here for an example: https://github.com/PythonNepal/pythonnepal.github.io/tree/source/content/pages

**Comment by code-geek** [comment]
@amitness Thanks, will do. I think I checked the wrong branch.

**Pull request closed without merging**
